---
- name: Clone dark theme repo
  ansible.builtin.git:
    repo: https://github.com/Weilbyte/PVEDiscordDark.git
    dest: /usr/local/lib/PVEDiscordDark
  notify: Install theme

- name: Create a symbolic link for offline install
  ansible.builtin.file:
    src: /usr/local/lib/PVEDiscordDark
    dest: /usr/local/lib/PVEDiscordDark/offline
    state: link

- name: Add dark theme dpkg Post-Invoke Hook
  ansible.builtin.copy:
    src: 99-proxmox-dark-theme
    dest: /etc/apt/apt.conf.d/99-proxmox-dark-theme
    mode: "0644"
